name: CI Workflow

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Run tests on PRs targeting the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Clone powsybl-openloadflow dependency
      - name: Clone powsybl-open-loadflow
        run: |
          git clone https://github.com/powsybl/powsybl-open-loadflow.git
          cd powsybl-open-loadflow
          mvn clean install -DskipTests
          cd ..

      # Set up Java and Maven
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Build and test your project
      - name: Build and test
        run: |
          mvn clean test

      # Upload test results
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/

      # Report test status
      - name: Annotate test results
        if: failure()
        uses: dorny/test-reporter@v1
        with:
          name: 'JUnit Tests'
          path: target/surefire-reports/*.xml
          reporter: java-junit
